#!/usr/bin/env python3
"""
Test Agent - A self-generated agent for testing swarm development capabilities.
Generated by: implementer agent during self-development assessment.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any, Dict, List, Optional

from shared.agent_base import BaseAgent, AgentConfig


class TestAgent(BaseAgent):
    """A specialized test agent that can perform code analysis and validation."""

    def __init__(self, config: AgentConfig, swarm_path: Optional[Path] = None, logs_dir: Optional[Path] = None):
        super().__init__(config, swarm_path, logs_dir)
        self.test_results: List[Dict[str, Any]] = []

    async def run_code_analysis(self, code_content: str) -> Dict[str, Any]:
        """Analyze code for potential issues and improvements."""
        analysis_prompt = f"""
        Please analyze the following code for:
        1. Potential bugs or security issues
        2. Code quality and style improvements
        3. Performance optimizations
        4. Architecture suggestions

        Code to analyze:
        ```python
        {code_content}
        ```

        Provide specific, actionable feedback.
        """
        
        response = await self.run_sync(analysis_prompt)
        
        result = {
            "timestamp": asyncio.get_event_loop().time(),
            "analysis": response,
            "code_length": len(code_content),
            "agent": self.name
        }
        
        self.test_results.append(result)
        return result

    async def validate_swarm_config(self, config_path: Path) -> Dict[str, Any]:
        """Validate a swarm configuration file."""
        if not config_path.exists():
            return {"error": f"Config file not found: {config_path}"}

        try:
            import yaml
            with open(config_path) as f:
                config = yaml.safe_load(f)
            
            validation_prompt = f"""
            Please validate this swarm configuration:
            
            {yaml.dump(config, default_flow_style=False)}
            
            Check for:
            - Required fields present
            - Valid agent roles and tools
            - Reasonable settings
            - Potential conflicts
            """
            
            response = await self.run_sync(validation_prompt)
            
            return {
                "config_valid": True,
                "validation_result": response,
                "config_path": str(config_path)
            }
            
        except Exception as e:
            return {"error": f"Failed to validate config: {e}"}

    def get_test_summary(self) -> Dict[str, Any]:
        """Get summary of all tests performed."""
        return {
            "total_tests": len(self.test_results),
            "results": self.test_results,
            "agent_info": {
                "name": self.name,
                "role": self.role,
                "model": self.config.model
            }
        }


def create_test_agent(name: str = "test_agent") -> TestAgent:
    """Factory function to create a test agent."""
    config = AgentConfig(
        name=name,
        role="tester",
        model="claude-sonnet-4-5-20250929",
        tools=["Read", "Write", "Glob", "Bash"],
        max_turns=20,
        system_prompt="""
        You are a specialized test agent created to assess the self-development capabilities 
        of the agent swarm system. Your role is to:
        
        1. Analyze code quality and identify improvements
        2. Validate system configurations
        3. Test inter-agent collaboration
        4. Assess system modification capabilities
        
        Be thorough, constructive, and focus on actionable feedback.
        """
    )
    
    return TestAgent(config)


if __name__ == "__main__":
    # Test the test agent
    agent = create_test_agent()
    print(f"Created test agent: {agent}")
    print(f"System prompt preview: {agent.system_prompt[:100]}...")